"""Steric-zipper interface analysis.

Two related but distinct computations:

1. `dry_interface_burial()` — the actual dry steric-zipper interface, computed
   on the real standalone hexapeptide microcrystal structures (2ON9 = VQIVYK,
   5V5C = VQIINK; see config data.zipper_reference_structures), using RCSB's
   own precomputed crystallographic assembly (`*-assembly1.cif`, symmetry
   mates already generated by RCSB's validated pipeline — not hand-rolled
   space-group math). This is what the "VQIINK buries ~2x VQIVYK" literature
   claim (Seidler 2018 Nat Chem) is actually about, and is what M11's
   `test_vqiink_buries_more_than_vqivyk` checks.

2. `window_buried_sasa()` — per-strain PHF6/PHF6* burial *within each disease
   fibril's own cross-beta stack* (a different quantity: how occluded that
   segment is by the fold's own architecture, used for the per-strain atlas
   characterization and the strain fingerprint, not for the zipper-burial
   literature comparison).

Shape-complementarity note: `packing_density_proxy()` reports a local heavy-
atom contact-density PROXY (min-max squashed to [0,1]), not the Lawrence &
Colman (1993) Sc statistic (which needs analytically-defined molecular
surfaces and dot-normal correlations — out of scope for a from-scratch CPU
implementation here). Documented, not passed off as the literature Sc value.
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import biotite.structure.io.pdbx as pdbx
import biotite.structure.io.pdb as pdb_io
import numpy as np

from sentinel.atlas.sasa import compute_residue_sasa, isolated_chain_sasa
from sentinel.utils.config import load_config, repo_path


_CHAIN_POOL = [chr(c) for c in list(range(65, 91)) + list(range(97, 123)) + list(range(48, 58))]


def _relabel_single_char_chains(arr):
    """PDB format allows only 1-char chain IDs; RCSB assembly files use
    multi-char IDs like 'A-10' for symmetry-generated copies. Remap to a
    single-char pool, preserving which atoms belong to the same original
    chain (order-independent for our purposes: we only need a consistent
    reference-chain selector and 'everything else')."""
    import numpy as np

    unique_ids = list(dict.fromkeys(arr.chain_id))  # stable order, first appearance
    mapping = {old: _CHAIN_POOL[i % len(_CHAIN_POOL)] for i, old in enumerate(unique_ids)}
    arr = arr.copy()
    arr.chain_id = np.array([mapping[c] for c in arr.chain_id])
    return arr, mapping


def _write_pdb(arr, dest: Path) -> None:
    writer = pdb_io.PDBFile()
    writer.set_structure(arr)
    writer.write(str(dest))


def dry_interface_burial(assembly_cif_path: str, reference_chain: str = "A") -> dict:
    """Buried SASA of `reference_chain` when packed against every other chain
    in the RCSB-precomputed crystallographic assembly, i.e. total burial due
    to real crystal contacts (dominated by the zipper interface in these
    single-hexapeptide microcrystals — there is essentially no other buried
    surface to compete with in a bare-peptide crystal)."""
    cif = pdbx.CIFFile.read(str(assembly_cif_path))
    arr = pdbx.get_structure(cif, model=1, use_author_fields=False)
    arr = arr[~arr.hetero]
    orig_chains = sorted(set(arr.chain_id))
    if reference_chain not in orig_chains:
        reference_chain = orig_chains[0]
    arr, mapping = _relabel_single_char_chains(arr)
    reference_chain = mapping[reference_chain]

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        ref_only_path = tmpdir / "ref_only.pdb"
        full_path = tmpdir / "full.pdb"
        _write_pdb(arr[arr.chain_id == reference_chain], ref_only_path)
        _write_pdb(arr, full_path)

        isolated = {r["res_id"]: r["sasa_A2"] for r in compute_residue_sasa(str(ref_only_path))}
        in_context = {r["res_id"]: r["sasa_A2"] for r in compute_residue_sasa(str(full_path))
                       if r["chain"] == reference_chain}

    per_residue = []
    for res_id in sorted(isolated):
        if res_id not in in_context:
            continue
        buried = max(isolated[res_id] - in_context[res_id], 0.0)
        per_residue.append({"res_id": res_id, "sasa_isolated_A2": round(isolated[res_id], 3),
                              "sasa_in_crystal_A2": round(in_context[res_id], 3),
                              "buried_A2": round(buried, 3)})
    total_buried = sum(r["buried_A2"] for r in per_residue)
    return {
        "reference_chain": reference_chain, "n_assembly_chains": len(orig_chains),
        "per_residue": per_residue, "total_buried_A2": round(total_buried, 3),
    }


def zipper_crystal_comparison() -> dict:
    cfg = load_config()
    refs = cfg["data"]["zipper_reference_structures"]
    results = {}
    for motif, spec in refs.items():
        assembly_path = repo_path("data", "raw", "structures", f"{spec['id']}-assembly1.cif")
        results[motif] = {"pdb_id": spec["id"], **dry_interface_burial(str(assembly_path))}
    vqivyk = results.get("VQIVYK", {}).get("total_buried_A2")
    vqiink = results.get("VQIINK", {}).get("total_buried_A2")
    ratio = (vqiink / vqivyk) if vqivyk else None
    return {**results, "VQIINK_over_VQIVYK_ratio": round(ratio, 3) if ratio else None}


# ------------------------------------------------------------------------------
# Per-strain in-fibril-context burial (distinct quantity — see module docstring)
# ------------------------------------------------------------------------------

def packing_density_proxy(stack_pdb: str, interior_chain: str, window_start: int,
                            window_end: int, contact_radius_A: float = 5.0) -> float:
    reader = pdb_io.PDBFile.read(str(stack_pdb))
    arr = reader.get_structure(model=1)
    arr = arr[arr.element != "H"]

    window_mask = ((arr.chain_id == interior_chain) & (arr.res_id >= window_start) &
                    (arr.res_id <= window_end))
    other_mask = arr.chain_id != interior_chain
    window_atoms, other_atoms = arr[window_mask], arr[other_mask]
    if window_atoms.array_length() == 0 or other_atoms.array_length() == 0:
        return 0.0

    diffs = window_atoms.coord[:, None, :] - other_atoms.coord[None, :, :]
    dists = np.linalg.norm(diffs, axis=-1)
    contacts_per_atom = (dists < contact_radius_A).sum(axis=1)
    mean_contacts = float(contacts_per_atom.mean())
    k = 8.0  # chosen so ~20 contacts/atom -> ~0.9; a fixed, documented squashing constant
    return round(mean_contacts / (mean_contacts + k), 4)


def window_buried_sasa(stack_pdb: str, interior_chain: str,
                         window_start: int, window_end: int) -> dict | None:
    stack_records = {r["res_id"]: r for r in compute_residue_sasa(stack_pdb) if r["chain"] == interior_chain}
    isolated = isolated_chain_sasa(stack_pdb, interior_chain)

    window_ids = list(range(window_start, window_end + 1))
    if not all(rid in stack_records and rid in isolated for rid in window_ids):
        return None  # this fold's ordered core does not span the full window (e.g. PiD excludes R2)

    per_residue = []
    for res_id in window_ids:
        sasa_stack = stack_records[res_id]["sasa_A2"]
        sasa_isolated = isolated[res_id]
        buried = max(sasa_isolated - sasa_stack, 0.0)
        per_residue.append({"res_id": res_id, "res_name": stack_records[res_id]["res_name"],
                              "sasa_isolated_A2": round(sasa_isolated, 3),
                              "sasa_in_stack_A2": round(sasa_stack, 3),
                              "buried_A2": round(buried, 3)})
    total_buried = sum(r["buried_A2"] for r in per_residue)
    return {"window_start": window_start, "window_end": window_end,
            "per_residue": per_residue, "total_buried_A2": round(total_buried, 3)}


def zipper_analysis_for_strain(strain_entry: dict, prepared_entry: dict) -> dict:
    cfg = load_config()
    lm = cfg["data"]["landmarks"]

    stack_pdb = str(repo_path(prepared_entry["stack_pdb"]))
    interior_chain = prepared_entry["stack_chains_used"][len(prepared_entry["stack_chains_used"]) // 2]

    phf6 = window_buried_sasa(stack_pdb, interior_chain, lm["PHF6"]["start"], lm["PHF6"]["end"])
    if phf6 is not None:
        phf6["packing_density_proxy"] = packing_density_proxy(
            stack_pdb, interior_chain, lm["PHF6"]["start"], lm["PHF6"]["end"])

    phf6_star = window_buried_sasa(stack_pdb, interior_chain, lm["PHF6_star"]["start"], lm["PHF6_star"]["end"])
    if phf6_star is not None:
        phf6_star["packing_density_proxy"] = packing_density_proxy(
            stack_pdb, interior_chain, lm["PHF6_star"]["start"], lm["PHF6_star"]["end"])

    return {
        "pdb_id": strain_entry["id"], "strain": strain_entry["strain"],
        "interior_chain_used": interior_chain,
        "PHF6_star_in_fibril_context": phf6_star, "PHF6_in_fibril_context": phf6,
    }
